name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

          file_name: .env
          fail_on_empty: false

      - name: Build Docker images
        run: |
          docker build . -t energaan:${{ github.sha }}

  run_app:
    runs-on: self-hosted
    needs: build

    steps:
      - name: remove running container
        run: |
          docker rm --force energaan

      - name: Run Docker images
        run: |
          docker run -d --restart unless-stopped -p 4200:3000 --name energaan energaan:${{ github.sha }}
